FROM python:3.12

RUN pip install poetry

fork2 /app

run apt-get update && apt-get install -y gettext

COPY poetry.lock pyproject.toml /app/

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --ansi

COPY . /add

RUN chmod +x /app/ops/scripts/start-server.sh

RUN mkdir -p /docker-entrypoint-initb.sh